# Custom Properties
customProperties.coach.name=Welcome-DEV-V1
customProperties.team.name=jasminetech-DEV
#------------------------------------------------------------------------------------------------------------------
#ClientDB
stclient.db_details.stclient_default=stclient_default
#stclient.db_details.stclient_iqraa=stclient_iqraa
#stclient.db_details.stclient_kanchan=stclient_kanchan
#stclient.db_details.stclient_dhills=stclient_dhills
#stclient.db_details.stclient_mahs=stclient_mahs
#stclient.db_details.stclient_mahsp=stclient_mahsp
#stclient.db_details.stclient_jfpl=stclient_jfpl
#stclient.db_details.stclient_jit=stclient_jit
stclient.db_details.stclient_ees=stclient_ees
#------------------------------------------------------------------------------------------------------------------
# Logging Configuration (Optimized)
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.validator=INFO
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
#------------------------------------------------------------------------------------------------------------------
# Show SQL queries (optional, but lighter than TRACE)
logging.level.org.hibernate.SQL=DEBUG
#------------------------------------------------------------------------------------------------------------------
# Management Configuration / Actuator Prperties
management.info.env.enabled=true
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info
#------------------------------------------------------------WhiteListedURL------------------------------------------------------
#whitelisted.url=http://192.168.29.57:5173
whitelisted.url=http://localhost:5173

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/docs
server.forward-headers-strategy=framework


