ALTER TABLE student
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER parent_actions;

ALTER TABLE teacher
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER documents;

ALTER TABLE parent
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER documents;

ALTER TABLE supervisor
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER documents;

ALTER TABLE admin
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER documents;


ALTER TABLE student
ADD COLUMN session VARCHAR(255) NOT NULL DEFAULT '2025-2026' AFTER parent_username;

ALTER TABLE student_exam
ADD COLUMN roll_no BIGINT AFTER class_name;

