# Custom Properties
customProperties.coach.name=Welcome-PROD-V1
customProperties.team.name=jasminetech-PROD
#------------------------------------------------------------------------------------------------------------------
#ClientDB
stclient.db_details.stclient_default=stclient_default
stclient.db_details.stclient_iqraa=stclient_iqraa
#stclient.db_details.stclient_kanchan=stclient_kanchan
stclient.db_details.stclient_dhills=stclient_dhills
stclient.db_details.stclient_mahs=stclient_mahs
stclient.db_details.stclient_mahsp=stclient_mahsp
stclient.db_details.stclient_jfpl=stclient_jfpl
stclient.db_details.stclient_jit=stclient_jit
stclient.db_details.stclient_ees=stclient_ees
#------------------------------------------------------------------------------------------------------------------
# Logging Configuration
logging.level.org.hibernate.validator=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR
#------------------------------------------------------------------------------------------------------------------
# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
#------------------------------------------------------------------------------------------------------------------
# Disable SQL logs
spring.jpa.show-sql=false
#------------------------------------------------------------------------------------------------------------------
# Flyway
spring.flyway.repair=false
#------------------------------------------------------------------------------------------------------------------
# CORS
whitelisted.url=https://jit.edu.in,https://www.jit.edu.in,https://eduemissary.com,https://www.eduemissary.com,https://www.jasminefiore.com,https://jasminefiore.com,https://api.eduemissary.com
#https://skoolish.online,https://www.skoolish.online,
