stclient.db_details.stclient_default=stclient_default
stclient.db_details.stclient_iqraa=stclient_iqraa
# stclient.db_details.stclient_kanchan=stclient_kanchan
#------------------------------------------------------------------------------------------------------------------
# Custom Properties
customProperties.coach.name=Self-Learner
customProperties.team.name=belbun
spring.application.name=schooltech-dev